language: java
jdk:
  - openjdk7

before_install:
 - chmod +x gradlew
 
install: ./gradlew setupCIWorkspace -S

script: 
 - ./gradlew build
 - ls -la build/libs
 
# Deploy the artifacts back to GitHub
deploy:
  provider: releases
  api_key: "ca3a06c1a8879fb27c97a1d36b6d058f33787bf4"
  file: "build/libs/growthcraft-2.2.2-complete.jar"
  skip_cleanup: true
  on:
    tags: true
